version: 2

sources:
  - name: ikondenko
    database: econ250-2025
    schema: ikondenko
    tables:
      - name: sheet_external
      - name: assignment1_full
  - name: google_trends
    database: bigquery-public-data
    schema: google_trends
    tables:
      - name: international_top_terms